sonic:
  agent:
    # 替换为部署Agent机器的ipv4
    host: ${AGENT_HOST:192.168.0.2}
    # 替换为Agent服务的端口，可以自行更改
    port: ${AGENT_PORT:7777}
    # 替换为前端新增Agent生成的key
    key: ${AGENT_KEY:235a35fd-5d0d-4533-905d-30d32902a12b}
  server:
    # 改成server的SONIC_SERVER_HOST
    host: ${SONIC_SERVER_HOST:192.168.1.1}
    # 改成server的SONIC_SERVER_PORT
    port: ${SONIC_SERVER_PORT:3000}

modules:
  android:
    # 是否开启安卓模块
    enable: ${ANDROID_ENABLE:true}
    # 是否开启sonic-android-supply远程adb调试功能
    use-sas: ${USE_SAS:true}
  ios:
    # 如果不需要连接iOS设备，请将true改为false。开启的windows用户请确保本机已安装iTunes
    enable: ${IOS_ENABLE:true}
    # 替换为你自己使用的wda的bundleId，如果没有.xctrunner后缀会自动补全，建议使用公司的开发者证书
    wda-bundle-id: ${WDA_BUNDLE_ID:com.facebook.WebDriverAgentRunner.xctrunner}
  sgm:
    enable: ${SGM_ENABLE:true}